# Generated by Django 5.0.7 on 2024-10-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("background_task", "0002_auto_20170927_1109"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="singleton",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                fields=("task_hash", "singleton"),
                name="background_task_task_unique_task_hash_singleton",
            ),
        ),
    ]
